---
name: CI

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  guardrails:
    uses: pr0d1r2/set-and-setting/.github/workflows/guardrails.yml@66d3b24969566859744c5dc911725dd6b97b9dec
